Repository codesquad-members-2023/be-java-lotto-max, pull requests merged in 2023-03, with the labels that each got.

#1 [Jinny] 로또 미션 학습 계획 작성
  README.md
Labels: documentation

#2 [Albert] 학습 계획 작성
  README.md
Labels: documentation

#3 [브루니] 학습계획 작성 / 로또 1단계 - 기본 기능 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/application/LotteryApplication.java
  src/main/java/kr/codesquad/domain/Lotteries.java
  src/main/java/kr/codesquad/domain/Lottery.java
  src/main/java/kr/codesquad/domain/PurchaseAmount.java
  src/main/java/kr/codesquad/domain/Result.java
  src/main/java/kr/codesquad/domain/Winning.java
  src/main/java/kr/codesquad/dto/ResultDto.java
  src/main/java/kr/codesquad/generator/LotteryNumberGenerator.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/PurchaseAmountTest.java
  src/test/java/kr/codesquad/domain/WinningTest.java
  src/test/java/kr/codesquad/generator/LotteryNumberGeneratorTest.java
Labels: documentation, enhancement

#4 [Ape] 학습 계획 작성
  README.md
  week2_plan.md
Labels: documentation

#5 [Jwon] 학습 계획
  README.md
Labels: documentation

#6 [sully] 학습 계획 작성과 클래스 설계 / 로또 1단계 - 기본 기능 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Lotto.java
  src/main/java/kr/codesquad/domain/LottoAmountInverter.java
  src/main/java/kr/codesquad/domain/LottoGenerator.java
  src/main/java/kr/codesquad/domain/LottoWinningStatisticsManager.java
  src/main/java/kr/codesquad/domain/Winning.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LottoAmountInverterTest.java
  src/test/java/kr/codesquad/domain/LottoGeneratorTest.java
  src/test/java/kr/codesquad/domain/LottoWinningStatisticsManagerTest.java
  src/test/java/kr/codesquad/domain/WinningTest.java
Labels: documentation, enhancement

#8 [Jinny] 로또 미션 1단계 일부 구현
  README.md
  build.gradle
  src/main/java/kr/codesquad/message/ErrorMessage.java
  src/main/java/kr/codesquad/model/Lotto.java
  src/main/java/kr/codesquad/model/Money.java
  src/main/java/kr/codesquad/service/LottoService.java
  src/main/java/kr/codesquad/util/LottoGenerator.java
  src/main/java/kr/codesquad/view/InputValidator.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/model/MoneyTest.java
Labels: enhancement

#9 [위즈] 학습 계획 작성
  README.md
Labels: documentation

#11 [Ayaan] 학습계획 작성 + Step-1 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Lotto.java
  src/main/java/kr/codesquad/domain/LottoGame.java
  src/main/java/kr/codesquad/domain/LottoLine.java
  src/main/java/kr/codesquad/view/Console.java
  src/test/java/domain/LottoLineTest.java
Labels: step-1, study plan

#12 [브루니] 학습계획 작성
  README.md
Labels: study plan

#15 [sully] 로또 2단계 - 보너스 번호 추가 구현
  src/main/java/kr/codesquad/LottoManager.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Lotto.java
  src/main/java/kr/codesquad/domain/LottoAmountInverter.java
  src/main/java/kr/codesquad/domain/LottoGenerator.java
  src/main/java/kr/codesquad/domain/LottoWinningStatisticsManager.java
  src/main/java/kr/codesquad/domain/Winning.java
  src/main/java/kr/codesquad/view/LottoInput.java
  src/main/java/kr/codesquad/view/LottoOutput.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LottoAmountInverterTest.java
  src/test/java/kr/codesquad/domain/LottoGeneratorTest.java
  src/test/java/kr/codesquad/domain/LottoWinningStatisticsManagerTest.java
  src/test/java/kr/codesquad/domain/WinningTest.java
Labels: step-2

#16 [브루니] 학습계획 작성
  README.md
Labels: study plan

#17 무비 - 로또 Step1 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Amount.java
  src/main/java/kr/codesquad/domain/AmountValidator.java
  src/main/java/kr/codesquad/domain/LottoGame.java
  src/main/java/kr/codesquad/domain/LottoNumberGenerator.java
  src/main/java/kr/codesquad/domain/PrizeCondition.java
  src/main/java/kr/codesquad/domain/PrizeConditionList.java
  src/main/java/kr/codesquad/domain/PrizeConditions/MatchingNumberCountCondition.java
  src/main/java/kr/codesquad/domain/PrizeType.java
  src/main/java/kr/codesquad/domain/StatisticMaker.java
  src/main/java/kr/codesquad/domain/Ticket.java
  src/main/java/kr/codesquad/domain/TicketMaker.java
  src/main/java/kr/codesquad/domain/WinningNumbers.java
  src/main/java/kr/codesquad/viewer/LottoInput.java
  src/main/java/kr/codesquad/viewer/LottoOutput.java
Labels: step-1

#18 [Albert] Step2 구현
  src/main/java/kr/codesquad/domain/Ball.java
  src/main/java/kr/codesquad/domain/LottoGame.java
  src/main/java/kr/codesquad/domain/LottoMachine.java
  src/main/java/kr/codesquad/domain/LottoManger.java
  src/main/java/kr/codesquad/domain/LottoResult.java
  src/main/java/kr/codesquad/domain/Prize.java
  src/main/java/kr/codesquad/domain/WinningNumbers.java
  src/main/java/kr/codesquad/view/InputManager.java
  src/main/java/kr/codesquad/view/OutputManager.java
  src/test/java/kr/codesquad/domain/LottoResultTest.java
  src/test/java/kr/codesquad/domain/PrizeTest.java
  src/test/java/kr/codesquad/domain/WinningNumbersTest.java
  src/test/java/kr/codesquad/view/InputManagerTest.java
Labels: step-2

#19 [위즈] Step-1 구현
  README.md
  src/main/java/kr/codesquad/LottoMain.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Lotto.java
  src/main/java/kr/codesquad/domain/LottoCustomer.java
  src/main/java/kr/codesquad/domain/LottoGame.java
  src/main/java/kr/codesquad/domain/Rank.java
  src/main/java/kr/codesquad/view/LottoInput.java
  src/main/java/kr/codesquad/view/LottoOutput.java
  src/test/java/kr/codesquad/domain/LottoCustomerTest.java
  src/test/java/kr/codesquad/domain/LottoTest.java
  src/test/java/kr/codesquad/domain/LuckyNumbersTest.java
  src/test/java/kr/codesquad/view/LottoInputTest.java
Labels: step-1

#20 [브루니] 로또 3단계 - 수동구매 기능 추가
  src/main/java/kr/codesquad/application/LotteryApplication.java
  src/main/java/kr/codesquad/domain/Lotteries.java
  src/main/java/kr/codesquad/domain/Lottery.java
  src/main/java/kr/codesquad/domain/Winning.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LotteryTest.java
Labels: step-3

#22 [Ayaan] Step-1 구현
  src/main/java/kr/codesquad/domain/Lotto.java
  src/main/java/kr/codesquad/domain/LottoGame.java
  src/main/java/kr/codesquad/domain/Prize.java
  src/main/java/kr/codesquad/view/Console.java
Labels: step-1

#23 [sully] step-3 적절한 예외 처리 방법 시도
  src/main/java/kr/codesquad/LottoManager.java
  src/main/java/kr/codesquad/domain/InputValidator.java
  src/main/java/kr/codesquad/domain/LottoAmountInverter.java
  src/main/java/kr/codesquad/domain/LottoGenerator.java
  src/main/java/kr/codesquad/domain/LottoWinningStatisticsManager.java
  src/main/java/kr/codesquad/domain/Winning.java
  src/main/java/kr/codesquad/view/LottoInput.java
  src/main/java/kr/codesquad/view/LottoOutput.java
  src/test/java/kr/codesquad/domain/LottoAmountInverterTest.java
  src/test/java/kr/codesquad/domain/LottoGeneratorTest.java
  src/test/java/kr/codesquad/domain/LottoWinningStatisticsManagerTest.java
  src/test/java/kr/codesquad/domain/WinningTest.java
Labels: step-3

#24 [Albert] 로또 Step3 구현
  src/main/java/kr/codesquad/domain/Ball.java
  src/main/java/kr/codesquad/domain/LottoBalls.java
  src/main/java/kr/codesquad/domain/LottoConfig.java
  src/main/java/kr/codesquad/domain/LottoGame.java
  src/main/java/kr/codesquad/domain/LottoMachine.java
  src/main/java/kr/codesquad/domain/LottoManger.java
  src/main/java/kr/codesquad/domain/LottoResult.java
  src/main/java/kr/codesquad/domain/Money.java
  src/main/java/kr/codesquad/domain/Player.java
  src/main/java/kr/codesquad/domain/Prize.java
  src/main/java/kr/codesquad/domain/Ticket.java
  src/main/java/kr/codesquad/domain/WinningNumbers.java
  src/main/java/kr/codesquad/view/InputManager.java
  src/main/java/kr/codesquad/view/OutputManager.java
  src/main/java/kr/codesquad/view/input/InputBonusBallManger.java
  src/main/java/kr/codesquad/view/input/InputManagerValidator.java
  src/main/java/kr/codesquad/view/input/InputManger.java
  src/main/java/kr/codesquad/view/input/InputManualLottoCountManager.java
  src/main/java/kr/codesquad/view/input/InputManualLottoNumbersManager.java
  src/main/java/kr/codesquad/view/input/InputPurchaseAmountManager.java
  src/main/java/kr/codesquad/view/input/InputWiningNumbersManager.java
  src/test/java/kr/codesquad/domain/BallTest.java
  src/test/java/kr/codesquad/domain/LottoMachineTest.java
  src/test/java/kr/codesquad/domain/LottoMangerTest.java
  src/test/java/kr/codesquad/domain/LottoResultTest.java
  src/test/java/kr/codesquad/domain/MoneyTest.java
  src/test/java/kr/codesquad/domain/PlayerTest.java
  src/test/java/kr/codesquad/domain/PrizeTest.java
  src/test/java/kr/codesquad/domain/TicketTest.java
  src/test/java/kr/codesquad/domain/WinningNumbersTest.java
  src/test/java/kr/codesquad/view/input/InputBonusBallMangerTest.java
  src/test/java/kr/codesquad/view/input/InputManagerValidatorTest.java
  src/test/java/kr/codesquad/view/input/InputManualLottoCountManagerTest.java
  src/test/java/kr/codesquad/view/input/InputManualLottoNumbersManagerTest.java
  src/test/java/kr/codesquad/view/input/InputPurchaseAmountManagerTest.java
  src/test/java/kr/codesquad/view/input/InputWiningNumbersManagerTest.java
Labels: step-3

#25 [위즈] Step-2 구현
  README.md
  src/main/java/kr/codesquad/domain/Config.java
  src/main/java/kr/codesquad/domain/Lotto.java
  src/main/java/kr/codesquad/domain/LottoCustomer.java
  src/main/java/kr/codesquad/domain/LottoGame.java
  src/main/java/kr/codesquad/domain/Rank.java
  src/main/java/kr/codesquad/domain/Validator.java
  src/main/java/kr/codesquad/view/LottoInput.java
  src/main/java/kr/codesquad/view/LottoOutput.java
  src/test/java/kr/codesquad/domain/LottoCustomerTest.java
  src/test/java/kr/codesquad/domain/LuckyNumbersTest.java
  src/test/java/kr/codesquad/view/LottoInputTest.java
Labels: step-2

#26 [Jwon] step-1 구현
  src/main/java/kr/codesquad/LottoMachine.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Lotto.java
  src/main/java/kr/codesquad/domain/LottoPapers.java
  src/main/java/kr/codesquad/view/InputView.java
Labels: step-1

#21 [브루니] 학습계획 작성
  README.md
Labels: study plan

#27 [Jinny] 로또 미션 - 2단계 구현
  README.md
  src/main/java/kr/codesquad/LottoController.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/config/Ranking.java
  src/main/java/kr/codesquad/message/ErrorMessage.java
  src/main/java/kr/codesquad/model/Lotto.java
  src/main/java/kr/codesquad/model/LottoNumber.java
  src/main/java/kr/codesquad/model/Lottos.java
  src/main/java/kr/codesquad/model/Money.java
  src/main/java/kr/codesquad/model/WinningLotto.java
  src/main/java/kr/codesquad/model/WinningResult.java
  src/main/java/kr/codesquad/service/LottoService.java
  src/main/java/kr/codesquad/util/LottoGenerator.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-2

#28 [Jwon] step-2 구현
  src/main/java/kr/codesquad/LottoMachine.java
  src/main/java/kr/codesquad/domain/Lotto.java
  src/main/java/kr/codesquad/domain/LottoPapers.java
  src/main/java/kr/codesquad/domain/LottoPrize.java
  src/main/java/kr/codesquad/domain/WinningLotto.java
  src/main/java/kr/codesquad/view/InputView.java
  src/test/java/WinningLottoTest.java
Labels: step-2

#30 [지구]Step-1 구현
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/LotteryGame.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/LotteryEntry.java
  src/main/java/kr/codesquad/domain/LotteryPrize.java
  src/main/java/kr/codesquad/domain/NumberMatcher.java
  src/main/java/kr/codesquad/domain/PrizeCalculator.java
  src/main/java/kr/codesquad/domain/QuickPick.java
  src/main/java/kr/codesquad/domain/Ticket.java
  src/main/java/kr/codesquad/util/Conversion.java
  src/main/java/kr/codesquad/util/Validation.java
  src/main/java/kr/codesquad/view/InputInfo.java
  src/main/java/kr/codesquad/view/OutputInfo.java
Labels: step-1
